### ISSUE TITLE
Integrate, Deploy to Firebase Hosting

### ISSUE THREAD

**Issue by heyhey1028** [heyhey1028/flutter_liff#1]
# Steps
- [x] install firebase-tools
```bash
$ npm install -g firebase-tools
```
- [x] Firebase settings for project
  - [x] Initialize with firebase cli
```bash
$ firebase init hosting
```

- [x] Flutter setting for deploying to Firebase Hosting
  - [x] Update firebase.json
  - [x] Update Github Action Workflow
  - [x] Update index.html
  - [x] Add `.firebase` folder to `gitignore`

# Reference
- https://qiita.com/fukusin/items/c5f5592b50101dfaea25
- https://zenn.dev/pressedkonbu/articles/deploy-flutter-web-app-with-firebase-hosting#5.-github-actions-%E3%81%AE%E6%89%8B%E7%9B%B4%E3%81%97
- https://stackoverflow.com/questions/52130772/whats-the-purpose-of-firebase-hosting-alphanum-cache

**Comment by heyhey1028** [comment]
# `firebase init hosting`での設定項目詳細
こちらの記事に詳細に記載有り
https://zenn.dev/pressedkonbu/articles/deploy-flutter-web-app-with-firebase-hosting
ありがとう、こんぶさん

```bash
# まずは初期化
[x] mba:~/development/material_icons% firebase init hosting

     ######## #### ########  ######## ########     ###     ######  ########
     ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##
     ######    ##  ########  ######   ########  #########  ######  ######
     ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##
     ##       #### ##     ## ######## ########  ##     ##  ######  ########

You're about to initialize a Firebase project in this directory:

  /Users/kenta/development/material_icons


=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

# すでにプロジェクトはあるのでそれを選ぶ
? Please select an option: Use an existing project
? Select a default Firebase project for this directory: material-icons-4aa2e (material-icons)
i  Using project material-icons-4aa2e (material-icons)

=== Hosting Setup

Your public directory is the folder (relative to your project directory) that
will contain Hosting assets to be uploaded with firebase deploy. If you
have a build process for your assets, use your build's output directory.

# ディレクトリはbuild/web
? What do you want to use as your public directory? build/web

# ちゃうはず
? Configure as a single-page app (rewrite all urls to /index.html)? No

# GitHub での自動デプロイやってくれるん？？ これをやってみよう
? Set up automatic builds and deploys with GitHub? Yes
✔  Wrote build/web/404.html
✔  Wrote build/web/index.html

# ブラウザが勝手に開かれるので承認する
i  Detected a .git folder at /Users/kenta/development/material_icons
i  Authorizing with GitHub to upload your service account to a GitHub repository's secrets store.

Visit this URL on this device to log in:
https://github.com/login/oauth/authorize?client_id=89cf50f02ac6aaed3484&state=752106639&redirect_uri=http%3A%2F%2Flocalhost%3A9005&scope=read%3Auser%20repo%20public_repo

Waiting for authentication...

✔  Success! Logged into GitHub as kenta-wakasa

# 作っておいたリポジトリの名前をにゅうりょく 今回は kenta-wakasa/material_icons
? For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) kenta-wakasa/material_icons

✔  Created service account github-action-330684705 with Firebase Hosting admin permissions.
✔  Uploaded service account JSON to GitHub as secret FIREBASE_SERVICE_ACCOUNT_MATERIAL_ICONS_4AA2E.
i  You can manage your secrets at https://github.com/kenta-wakasa/material_icons/settings/secrets.

# やってくれるならやってほしいので Yes たぶん勝手ににワークフローを書いてくれる。
? Set up the workflow to run a build script before every deploy? Yes

# どうせ動かないけどいったん flutter build web と答えておく
? What script should be run before every deploy? flutter build web

✔  Created workflow file /Users/kenta/development/material_icons/.github/workflows/firebase-hosting-pull-request.yml

# PR がマージされたとき deploy するやんな
? Set up automatic deployment to your site's live channel when a PR is merged? Yes

# main です
? What is the name of the GitHub branch associated with your site's live channel? main

✔  Created workflow file /Users/kenta/development/material_icons/.github/workflows/firebase-hosting-merge.yml

i  Action required: Visit this URL to revoke authorization for the Firebase CLI GitHub OAuth App:
https://github.com/settings/connections/applications/89cf50f02ac6aaed3484
i  Action required: Push any new workflow file(s) to your repo

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!

```

**Comment by heyhey1028** [comment]
# Flutter側の設定
## Update firebase.json
`firebase.json`の`public`が`build/web`になっている事を確認。
```json
{
  "hosting": {
    "public": "build/web", 
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ]
  }
}

```

背景：
- `flutter build web`を叩いた際にコンパイルされたファイルが`build/web`に作成される。
- firebase initのデフォルト設定ではルートディレクトリのpublicフォルダのindex.htmlをデプロイする設定になっている。

## Update github actions workflow
これもこちらの記事に詳細が書いてある。
https://zenn.dev/pressedkonbu/articles/deploy-flutter-web-app-with-firebase-hosting#5.-github-actions-%E3%81%AE%E6%89%8B%E7%9B%B4%E3%81%97

これをしないとPRを出した際やmainブランチにマージした際に自動的に走るデプロイのActionsがコケてしまう。
```yaml
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools

name: Deploy to Firebase Hosting on merge
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # -- ここから追記部分！ -- #
      # Flutter のインストール clone がはやい
      - name: Install Flutter
        run: git clone https://github.com/flutter/flutter.git

      # PATH を通す
      - name: Add path
        run: echo "$(pwd)/flutter/bin" >> $GITHUB_PATH

      # パッケージのダウンロード
      - name: Download Flutter packages
        run: flutter pub get

      # -- ここまで追記部分！ -- #
      # 解説:
      #   ようは flutter build web をたたいても flutterがインストールされていないので動かないということ
      #   インストールしてPATH通してパッケージダウンロードしているだけ。

      # ビルド
      - run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATERIAL_ICONS_4AA2E }}"
          channelId: live
          projectId: material-icons-4aa2e
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
```

## Update index.html
これは今回初めて知ったor何かProject作成する時にミスったのかもしれないが、`main.dart`のファイルは`web/index.html`に下記の記述を追加しないとデプロイするindex.htmlに連携されない。
この記述を追加しないとどんなに`flutter build web`してもmain.dartがwebアプリに含まれない。
```html
<script src="main.dart.js" type="application/javascript"></script>
```

## Add .firebase folder to gitignore
これら設定の過程で生成される`.firebase`フォルダはgitignoreしてヨシ
https://stackoverflow.com/questions/52130772/whats-the-purpose-of-firebase-hosting-alphanum-cache
